update readme and add fly in + call me maybe

diff --git a/42cursus/Circle 3/Call_Me_Maybe/Makefile b/42cursus/Circle 3/Call_Me_Maybe/Makefile
--- a/42cursus/Circle 3/Call_Me_Maybe/Makefile
+++ b/42cursus/Circle 3/Call_Me_Maybe/Makefile
@@ -3,10 +3,10 @@
 #                                                      :::      ::::::::    #
 #  Makefile                                          :+:      :+:    :+:    #
 #                                                  +:+ +:+         +:+      #
-#  By: roandrie <roandrie@student.42.fr>         +#+  +:+       +#+         #
+#  By: roandrie <roandrie@student.42lehavre.fr   +#+  +:+       +#+         #
 #                                              +#+#+#+#+#+   +#+            #
 #  Created: 2026/02/23 16:32:54 by roandrie        #+#    #+#               #
-#  Updated: 2026/02/23 17:21:40 by roandrie        ###   ########.fr        #
+#  Updated: 2026/04/24 15:53:20 by roandrie        ###   ########.fr        #
 #                                                                           #
 # ************************************************************************* #
 
@@ -19,25 +19,33 @@ FLAKE8		=	uv run flake8
 MYPY 		=	uv run mypy
 MYPY_FLAGS	=	--warn-return-any --warn-unused-ignores --ignore-missing-imports --disallow-untyped-defs --check-untyped-defs
 SRC_MODULE	=	src
-UV			=	curl -LsSf https://astral.sh/uv/install.sh | sh
+INSTALL_UV	=	curl -LsSf https://astral.sh/uv/install.sh | sh
+CHECK_UV	=	command -v uv
+UV_WARN		=	--link-mode copy
+LINT_TESTER =	src \
+				tests
 
 # ===================
 # =		RULES		=
 # ===================
 
-.PHONY:		all install run debug clean lint lint-strict
+.PHONY:		all install run debug clean lint lint-strict delete-uv tester
 .SILENT:
 
 all:		install run
 
 install:
+			@if	! $(CHECK_UV) > /dev/null 2>&1; then \
+					echo "$(BRED)UV not installed. Installing...$(RESET)"; \
+					$(INSTALL_UV); \
+			fi
 			@echo "$(BGREEN)Installing project dependencies using uv...$(RESET)"
-			uv sync
+			uv sync $(UV_WARN)
 
-run:
+run:		install
 			$(PYTHON) -m $(SRC_MODULE)
 
-debug:
+debug:		install
 			@echo "$(BGREEN)Running the main script in debug mode...$(RESET)"
 			$(PDB) -m $(SRC_MODULE)
 
@@ -50,14 +58,33 @@ clean:
 			rm -rf .pytest_cache
 
 lint:
+			@clear
 			@echo "$(BMAGENTA)Running standard linting...$(RESET)"
-			$(FLAKE8) $(SRC_MODULE)
-			$(MYPY) $(SRC_MODULE) $(MYPY_FLAGS)
+			@status=0; \
+			$(FLAKE8) $(LINT_TESTER) || status=$$?; \
+			$(MYPY) $(LINT_TESTER) $(MYPY_FLAGS) || status=$$?; \
+			exit $$status
 
 lint-strict:
+			@clear
 			@echo "$(BMAGENTA)Running strict linting...$(RESET)"
-			$(FLAKE8) $(SRC_MODULE)
-			$(MYPY) $(SRC_MODULE) --strict
+			@status=0; \
+			$(FLAKE8) $(LINT_TESTER) || status=$$?; \
+			$(MYPY) $(LINT_TESTER) $(MYPY_FLAGS) --strict || status=$$?; \
+			exit $$status
+
+delete-uv:
+			@if $(CHECK_UV) > /dev/null 2>&1; then \
+					echo "$(BRED)Deleting uv...$(RESET)"; \
+					rm -f $$(which uv); \
+			else \
+					echo "$(BRED)UV not installed. Cannot delete. Abording.$(RESET)"; \
+			fi
+
+tester:
+			install
+			uv run python -m unittest discover -s tests
+
 
 # ===================
 # =		COLORS		=
@@ -67,3 +94,4 @@ RESET		=	\033[0m
 BGREEN		=	\033[92m
 BMAGENTA	=	\033[95m
 YELLOW		=	\033[93m
+BRED		=	\033[91m
diff --git a/42cursus/Circle 3/Fly-in/Makefile b/42cursus/Circle 3/Fly-in/Makefile
--- a/42cursus/Circle 3/Fly-in/Makefile
+++ b/42cursus/Circle 3/Fly-in/Makefile
@@ -3,10 +3,10 @@
 #                                                      :::      ::::::::    #
 #  Makefile                                          :+:      :+:    :+:    #
 #                                                  +:+ +:+         +:+      #
-#  By: roandrie <roandrie@student.42.fr>         +#+  +:+       +#+         #
+#  By: roandrie <roandrie@student.42lehavre.fr   +#+  +:+       +#+         #
 #                                              +#+#+#+#+#+   +#+            #
 #  Created: 2026/02/23 18:22:36 by roandrie        #+#    #+#               #
-#  Updated: 2026/02/23 18:22:54 by roandrie        ###   ########.fr        #
+#  Updated: 2026/03/24 10:39:37 by roandrie        ###   ########.fr        #
 #                                                                           #
 # ************************************************************************* #
 
@@ -19,25 +19,36 @@ FLAKE8		=	uv run flake8
 MYPY 		=	uv run mypy
 MYPY_FLAGS	=	--warn-return-any --warn-unused-ignores --ignore-missing-imports --disallow-untyped-defs --check-untyped-defs
 SRC_MODULE	=	src
-UV			=	curl -LsSf https://astral.sh/uv/install.sh | sh
+INSTALL_UV	=	curl -LsSf https://astral.sh/uv/install.sh | sh
+CHECK_UV	=	command -v uv
+
+# Launch with a custom map. Use "make run M=<path to map>"
+M			=
 
 # ===================
 # =		RULES		=
 # ===================
 
-.PHONY:		all install run debug clean lint lint-strict
+.PHONY:		all install run run-script run-debug debug clean lint lint-strict delete-uv
 .SILENT:
 
 all:		install run
 
 install:
+			@if	! $(CHECK_UV) > /dev/null 2>&1; then \
+					echo "$(BRED)UV not installed. Installing...$(RESET)"; \
+					$(INSTALL_UV); \
+			fi
 			@echo "$(BGREEN)Installing project dependencies using uv...$(RESET)"
 			uv sync
 
 run:
-			$(PYTHON) -m $(SRC_MODULE)
+			$(PYTHON) -m $(SRC_MODULE) $(M)
 
-debug:
+run-debug:
+			$(PYTHON) -m $(SRC_MODULE) $(M) --debug
+
+debug:		install
 			@echo "$(BGREEN)Running the main script in debug mode...$(RESET)"
 			$(PDB) -m $(SRC_MODULE)
 
@@ -50,14 +61,28 @@ clean:
 			rm -rf .pytest_cache
 
 lint:
+			@clear
 			@echo "$(BMAGENTA)Running standard linting...$(RESET)"
-			$(FLAKE8) $(SRC_MODULE)
-			$(MYPY) $(SRC_MODULE) $(MYPY_FLAGS)
+			@status=0; \
+			$(FLAKE8) $(SRC_MODULE) || status=$$?; \
+			$(MYPY) $(SRC_MODULE) $(MYPY_FLAGS) || status=$$?; \
+			exit $$status
 
 lint-strict:
+			@clear
 			@echo "$(BMAGENTA)Running strict linting...$(RESET)"
-			$(FLAKE8) $(SRC_MODULE)
-			$(MYPY) $(SRC_MODULE) --strict
+			@status=0; \
+			$(FLAKE8) $(SRC_MODULE) || status=$$?; \
+			$(MYPY) $(SRC_MODULE) $(MYPY_FLAGS) --strict || status=$$?; \
+			exit $$status
+
+delete-uv:
+			@if $(CHECK_UV) > /dev/null 2>&1; then \
+					echo "$(BRED)Deleting uv...$(RESET)"; \
+					rm -f $$(which uv); \
+			else \
+					echo "$(BRED)UV not installed. Cannot delete. Abording.$(RESET)"; \
+			fi
 
 # ===================
 # =		COLORS		=
@@ -67,3 +92,4 @@ RESET		=	\033[0m
 BGREEN		=	\033[92m
 BMAGENTA	=	\033[95m
 YELLOW		=	\033[93m
+BRED		=	\033[91m
